### PR TITLE
allow dash in catkin package names

### PR DESCRIPTION
**Pull request by dirk-thomas**
Replaces #182.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@dirk-thomas wrote (in #182):
> I just hope we will not run into the problem of duplicate package names afterwards or uncertainty about how the CMake variables are being exported (since that was a main reason why this rule enforced uniqueness and consistency).

can you say anything about the exported CMake variables? Would the dashes be retained there?

**Comment by dirk-thomas** [comment]
> can you say anything about the exported CMake variables? Would the dashes be retained there?

CMake variables can't contain dashes.

**Comment by gavanderhoorn** [comment]
> CMake variables can't contain dashes.

exactly, so will the variables for those pkgs have underscores instead then? Is that the potential confusion you are referring to?

**Comment by dirk-thomas** [comment]
> so will the variables for those pkgs have underscores instead then? Is that the potential confusion you are referring to?

Yes, I would assume using underscores would be a reasonable mapping.

A package name with dashes is more common for e.g. Python packages though. I hope this won't be used for CMake packages often.

**Comment by dirk-thomas** [comment]
@ros-infrastructure/ros_team Please review.

**Comment by wjwwood** [comment]
> CMake variables can't contain dashes.

Actually that's not true (/shudder) 🤢:

```
william@johnnycake /tmp
% cat test.cmake
set(a-dash "Hello World!")
message(STATUS ${a-dash})

william@johnnycake /tmp
% cmake -P test.cmake
-- Hello World!
```

**Comment by dirk-thomas** [comment]
> > CMake variables can't contain dashes.

> Actually that's not true (/shudder) :nauseated_face::

Interesting, that is the first time I have seen that but the [docs](https://cmake.org/cmake/help/v3.0/manual/cmake-language.7.html#variables) "agree" with it.

**Pull request merged**
