### PR TITLE
Flake8, #210

### LINKED ISSUE #210: flake8 integration
I'd like to add flake8 integration to this project, as it is done in [https://github.com/ros-infrastructure/rosdep](https://github.com/ros-infrastructure/rosdep) - with a new unit test that runs flake8.

Ideas/objections?

### PR DESCRIPTION
**Pull request by Nickolaim**
Runs Flake8 as a unit test.  Same rules as in rosdep.  Added Python 3.6 as a job in Travis CI.  Fixed issues raised by flake8.

Closes #210.

### CODE REVIEW

**Comment by Nickolaim** [comment]
flake8 is not supported in Python 3.2 and 3.3 - see Categories at [https://pypi.python.org/pypi/flake8](https://pypi.python.org/pypi/flake8)

**Comment by Nickolaim** [comment]
@dirk-thomas What about this PR?  It is an initial effort to have flake8 running in this repo.  More cleanup needs to happen in the future + plugins to be on the same level as in ament_flake8.

**Comment by dirk-thomas** [comment]
I added a few cleanup commits. But the remaining test failures require a rebase since they are coming from code pieces which have changed on the target branch since this branch was forked.

**Comment by Nickolaim** [comment]
Done.  Please review.

**Comment by dirk-thomas** [comment]
Looks good. Thank you for working on this.

**Pull request merged**
