### PR TITLE
Use only first line of description in distutils setup generation

### PR DESCRIPTION
**Pull request by cottsay**
This is an alternative to #316 that uses only the first line of the package description in the Python distutils setup rather than converting line breaks to spaces.

I'd like to hear feedback on which approach is preferable.

### CODE REVIEW

**Review by nuclearsandwich — APPROVED** [review]
I prefer this approach compared with both #316 and the base branch implementation. It has a much better chance of producing an intelligible description within the restrictions of the setuptools description format.

I wonder if it's worth adding any kind of style convention to the package creation documentation espousing the `Subject line\n\nLong description\n` pattern but it shouldn't block this PR.

**Comment by cottsay** [comment]
Depends on #329

**Comment by cottsay** [comment]
Okay, this is looking pretty good. For example:
Before:
```
Summary: The actionlib stack provides a standardized interface for     interfacing with preemptable tasks. Examples of this include moving     the base to a target location, performing a laser scan and retu...
```
After:
```
Summary: The actionlib stack provides a standardized interface for interfacing with preemptable tasks. Examples of this include moving the base to a target location, performing a laser scan and returning th...
```

Dropping a `<br/>` after the first sentence makes this even better:
```
Summary: The actionlib stack provides a standardized interface for interfacing with preemptable tasks.
```

**Review by nuclearsandwich — APPROVED** [review]
Updating my approval to the version of this based on the plaintext_description attribute.

**Pull request merged**
