### PR TITLE
fix regression

### PR DESCRIPTION
**Pull request by dirk-thomas**
Introduced in #171 when no packages are found.

### CODE REVIEW

**Comment by ipa-mdl** [comment]
Not sure if it is intended, but `ros-shadow-fixed` still ships `0.3.2`.

**Comment by dirk-thomas** [comment]
@ipa-mdl No, not intended. Thanks for reporting. We are already trying to fix the problem...

**Comment by dirk-thomas** [comment]
@ipa-mdl As a workaround you can switch to the "public" repo, update `python-catkin-pkg` and `python-catkin-pkg-modules`, and switch back to the "shadow-fixed" repo.

**Comment by dirk-thomas** [comment]
All resolved by now - all repos finally have the latest version...

**Comment by ipa-mdl** [comment]
> All resolved by now - all repos finally have the latest version...

I cannot confirm it:
[packages.ros.org/ros/](http://packages.ros.org/ros/ubuntu/dists/trusty/main/binary-amd64/Packages): 0.3.1-1
[packages.ros.org/ros-shadow-fixed/](http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/trusty/main/binary-amd64/Packages): 0.3.2-1
repositories.ros.org/ubuntu/{main,testing}: 0.3.3-1

**Comment by dirk-thomas** [comment]
My previous comment was based on the status pages (e.g. http://repositories.ros.org/status_page/kinetic_default.html?q=catkin-pkg). The public apt repo always "lags" a little bit behind. Shadow fixed has been synced over night  already. The main repo will only sync once any of the ROS distros is being synced.

**Comment by ipa-mdl** [comment]
Our travis jobs are green again, thanks!

**Comment by dirk-thomas** [comment]
Sorry for inconvenience!

**Comment by mikepurvis** [comment]
Thanks for cleaning this up. Sorry my little change ended up causing so much drama.

**Pull request merged**
