### PR TITLE
catkin_create_pkg use package.xml format 2

### LINKED ISSUE #96: catkin_create_pkg: start using package.xml format 2

### PR DESCRIPTION
**Pull request by scpeters**
This is a work-in-progress to resolve #96. I tried updating it to match the new tags, but I haven't tested it yet.

### CODE REVIEW

**Comment by scpeters** [comment]
CI is green now, but I haven't tested it locally. I'm guessing that it won't ever produce `<depend>` tags in the output since I didn't adapt the [merge logic for run_depends](https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/package.py#L108-L113) to the `depends` tag.

**Comment by scpeters** [comment]
I just squashed some of the embarrassing commits. It should be ready for review.

**Comment by dirk-thomas** [comment]
> CI is green now, but I haven't tested it locally.
> It should be ready for review.

Please go ahead and test the changes locally before requesting a review.

**Comment by scpeters** [comment]
Here's what it generates for the [beginner_tutorials package.xml](http://wiki.ros.org/ROS/Tutorials/catkin/CreatingPackage#Creating_a_catkin_Package) when I run it locally:

~~~
<?xml version="1.0"?>
<package format="2">
  <name>beginner_tutorials</name>
  <version>0.0.0</version>
  <description>The beginner_tutorials package</description>

  <!-- One maintainer tag required, multiple allowed, one person per tag -->
  <!-- Example:  -->
  <!-- <maintainer email="jane.doe@example.com">Jane Doe</maintainer> -->
  <maintainer email="scpeters@todo.todo">scpeters</maintainer>


  <!-- One license tag required, multiple allowed, one license per tag -->
  <!-- Commonly used license strings: -->
  <!--   BSD, MIT, Boost Software License, GPLv2, GPLv3, LGPLv2.1, LGPLv3 -->
  <license>TODO</license>


  <!-- Url tags are optional, but multiple are allowed, one per tag -->
  <!-- Optional attribute type can be: website, bugtracker, or repository -->
  <!-- Example: -->
  <!-- <url type="website">http://wiki.ros.org/beginner_tutorials</url> -->


  <!-- Author tags are optional, multiple are allowed, one per tag -->
  <!-- Authors do not have to be maintainers, but could be -->
  <!-- Example: -->
  <!-- <author email="jane.doe@example.com">Jane Doe</author> -->


  <!-- The *depend tags are used to specify dependencies -->
  <!-- Dependencies can be catkin packages or system dependencies -->
  <!-- Examples: -->
  <!-- Use build_depend for packages you need at compile time: -->
  <!--   <build_depend>message_generation</build_depend> -->
  <!-- Use build_export_depend for packages you need in order to build against this package: -->
  <!--   <build_export_depend>message_generation</build_export_depend> -->
  <!-- Use buildtool_depend for build tool packages: -->
  <!--   <buildtool_depend>catkin</buildtool_depend> -->
  <!-- Use doc_depend for packages you need only for building documentation: -->
  <!--   <doc_depend>gtest</doc_depend> -->
  <!-- Use exec_depend for packages you need at runtime: -->
  <!--   <exec_depend>message_runtime</exec_depend> -->
  <!-- Use test_depend for packages you need only for testing: -->
  <!--   <test_depend>gtest</test_depend> -->
  <!-- Use depend as a shortcut for packages that are both build and runtime dependencies -->
  <!--   <depend>roscpp</depend> -->
  <!--   Note that this is equivalent to the following: -->
  <!--   <build_depend>roscpp</build_depend> -->
  <!--   <build_export_depend>roscpp</build_export_depend> -->
  <!--   <exec_depend>roscpp</exec_depend> -->
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>


  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
~~~

It would be nicer if it grouped them into the `<depend>` tag.

**Comment by scpeters** [comment]
@dirk-thomas I have tested it locally.

**Comment by dirk-thomas** [comment]
> I have tested it locally.

That is great.

Currently I have to focus on ROS 2 related task so it might take a bit until I will have the time to review this. Sorry.

**Comment by scpeters** [comment]
Thanks for the improvements to those comments.

I think it is already backwards compatible, since I updated one of the tests to use the new format version 2 and it has some `run_depends`:

* https://github.com/scpeters/catkin_pkg/blob/4b7897417d04ecf98a0ddd7d90249fdd96afb48c/test/test_templates.py#L206-L268

**Comment by dirk-thomas** [comment]
Thank you for working on this and iterating on the patch.

**Comment by gavanderhoorn** [comment]
It would appear that the merge of this PR causes problems with the "CreatingMsgAndSrv" tutorial (among others) on the wiki, as the text instructs users to add `run_depend`s in a few places, which with `catkin_create_pkg` generating format 2 manifests then results in errors/warnings.

See [Tutorials: package format 2 vs format 1](https://answers.ros.org/question/274199) on ROS Answers.

**Comment by dirk-thomas** [comment]
I updated the code snippets coming from [catkin_tutorials](https://github.com/ros/catkin_tutorials/pull/11) as well as a couple of wiki pages:

* http://wiki.ros.org/action/diff/ROS/Tutorials/catkin/CreatingPackage?action=diff&rev1=32&rev2=33
* http://wiki.ros.org/action/diff/ROS/Tutorials/CreatingMsgAndSrv?action=diff&rev1=132&rev2=133

**Comment by gavanderhoorn** [comment]
Awesome.

Didn't mean to dump this on anyone (you).

Thanks for fixing 🍻

**Comment by mikaelarguedas** [comment]
@scpeters It looks like the comment "It would be nicer if it grouped them into the <depend> tag." has not been addressed. Was it purposefully not changed, left up for a follow-up PR or just overlooked ?

**Comment by scpeters** [comment]
I would say that it's left for a follow-up PR. I didn't think of a quick and easy way to do it; so I just left the comment instead.

**Comment by mikaelarguedas** [comment]
:+1: thanks for clarifying

**Pull request merged**
