### PR TITLE
Converted python package declaration to ament style.

### PR DESCRIPTION
**Pull request by ernestmc**
Needed changes so the python package installs correctly under ament.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I don't think it is necessary to move all the files in order to work with `ament`. Can you please describe why you think it is not possible without.

**Comment by ernestmc** [comment]
@dirk-thomas if the python package ```catkin_pkg``` is inside the ```src``` folder ament isn't able to find it. I checked [ament_package](https://github.com/ament/ament_package) and followed a similar structure and so it worked.

**Comment by dirk-thomas** [comment]
Ament uses plain setup.py files so I can't imagine why it wouldn't support that use case. If there is a corner case which is not covered right now that should be addressed instead of forcing packages to restructure.

**Comment by ernestmc** [comment]
I agree. I'm the only one having this issue. I'll close this pull request and investigate further why is this happening.

**Pull request closed without merging**
